app = "streamnzb"
primary_region = "lhr"

[build]
image = "ghcr.io/gaisberg/streamnzb:latest"

[env]
TZ = "Europe/London"

[[services]]
internal_port = 7000
protocol = "tcp"

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[[services]]
internal_port = 1119
protocol = "tcp"

[[services.ports]]
port = 1119

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
